// English error messages for tjscheck standalone syntax checker
// Based on tjsError_jp.h from tjsdisasm, translated to English
#ifndef __TJS_ERROR_INC_H__
#define __TJS_ERROR_INC_H__
TJS_MSG_DECL(TJSInternalError, TJS_W("Internal error"))
TJS_MSG_DECL(TJSWarning, TJS_W("Warning: "))
TJS_MSG_DECL(TJSWarnEvalOperator, TJS_W("Using comma operator outside of global scope"))
TJS_MSG_DECL(TJSNarrowToWideConversionError, TJS_W("Cannot convert ANSI string to Unicode"))
TJS_MSG_DECL(TJSVariantConvertError, TJS_W("Cannot convert %1 to %2"))
TJS_MSG_DECL(TJSVariantConvertErrorToObject, TJS_W("Cannot convert %1 to Object"))
TJS_MSG_DECL(TJSIDExpected, TJS_W("Identifier expected"))
TJS_MSG_DECL(TJSSubstitutionInBooleanContext, TJS_W("Substitution (=) in boolean context (did you mean ==?)"))
TJS_MSG_DECL(TJSCannotModifyLHS, TJS_W("Cannot modify left-hand side"))
TJS_MSG_DECL(TJSInsufficientMem, TJS_W("Insufficient memory"))
TJS_MSG_DECL(TJSCannotGetResult, TJS_W("Cannot get result from this expression"))
TJS_MSG_DECL(TJSNullAccess, TJS_W("Accessing null object"))
TJS_MSG_DECL(TJSMemberNotFound, TJS_W("Member '%1' not found"))
TJS_MSG_DECL(TJSMemberNotFoundNoNameGiven, TJS_W("Member not found"))
TJS_MSG_DECL(TJSNotImplemented, TJS_W("Not implemented"))
TJS_MSG_DECL(TJSInvalidParam, TJS_W("Invalid parameter"))
TJS_MSG_DECL(TJSBadParamCount, TJS_W("Bad parameter count"))
TJS_MSG_DECL(TJSInvalidType, TJS_W("Invalid type"))
TJS_MSG_DECL(TJSSpecifyDicOrArray, TJS_W("Specify a Dictionary or Array object"))
TJS_MSG_DECL(TJSSpecifyArray, TJS_W("Specify an Array object"))
TJS_MSG_DECL(TJSStringDeallocError, TJS_W("String deallocation error"))
TJS_MSG_DECL(TJSStringAllocError, TJS_W("String allocation error"))
TJS_MSG_DECL(TJSMisplacedBreakContinue, TJS_W("Misplaced break/continue"))
TJS_MSG_DECL(TJSMisplacedCase, TJS_W("Misplaced case"))
TJS_MSG_DECL(TJSMisplacedReturn, TJS_W("Misplaced return"))
TJS_MSG_DECL(TJSStringParseError, TJS_W("Unterminated string literal"))
TJS_MSG_DECL(TJSNumberError, TJS_W("Invalid numeric literal"))
TJS_MSG_DECL(TJSUnclosedComment, TJS_W("Unterminated comment"))
TJS_MSG_DECL(TJSInvalidChar, TJS_W("Invalid character: '%1'"))
TJS_MSG_DECL(TJSExpected, TJS_W("%1 expected"))
TJS_MSG_DECL(TJSSyntaxError, TJS_W("Syntax error"))
TJS_MSG_DECL(TJSPPError, TJS_W("Preprocessor error"))
TJS_MSG_DECL(TJSCannotGetSuper, TJS_W("Cannot get super class"))
TJS_MSG_DECL(TJSInvalidOpecode, TJS_W("Invalid VM opcode"))
TJS_MSG_DECL(TJSRangeError, TJS_W("Value out of range"))
TJS_MSG_DECL(TJSAccessDenyed, TJS_W("Access denied"))
TJS_MSG_DECL(TJSNativeClassCrash, TJS_W("Native class crash"))
TJS_MSG_DECL(TJSInvalidObject, TJS_W("Invalid object (already released)"))
TJS_MSG_DECL(TJSCannotOmit, TJS_W("Cannot use '...' here"))
TJS_MSG_DECL(TJSCannotParseDate, TJS_W("Cannot parse date/time"))
TJS_MSG_DECL(TJSInvalidValueForTimestamp, TJS_W("Invalid value for timestamp"))
TJS_MSG_DECL(TJSExceptionNotFound, TJS_W("Exception class not found"))
TJS_MSG_DECL(TJSInvalidFormatString, TJS_W("Invalid format string"))
TJS_MSG_DECL(TJSDivideByZero, TJS_W("Division by zero"))
TJS_MSG_DECL(TJSNotReconstructiveRandomizeData, TJS_W("Cannot reproduce random sequence"))
TJS_MSG_DECL(TJSSymbol, TJS_W("identifier"))
TJS_MSG_DECL(TJSCallHistoryIsFromOutOfTJS2Script, TJS_W("[Out of TJS2 script scope]"))
TJS_MSG_DECL(TJSNObjectsWasNotFreed, TJS_W("%1 objects were not freed"))
TJS_MSG_DECL(TJSObjectCreationHistoryDelimiter, TJS_W("\n                     "))
TJS_MSG_DECL(TJSObjectWasNotFreed, TJS_W("Object %1 [%2] was not freed. Creation trace:\n                     %3"))
TJS_MSG_DECL(TJSGroupByObjectTypeAndHistory, TJS_W("Group by object type and creation trace"))
TJS_MSG_DECL(TJSGroupByObjectType, TJS_W("Group by object type"))
TJS_MSG_DECL(TJSObjectCountingMessageGroupByObjectTypeAndHistory, TJS_W("%1 count: [%2]\n                     %3"))
TJS_MSG_DECL(TJSObjectCountingMessageTJSGroupByObjectType, TJS_W("%1 count: [%2]"))
TJS_MSG_DECL(TJSWarnRunningCodeOnDeletingObject, TJS_W("Code running during object deletion"))
TJS_MSG_DECL(TJSWriteError, TJS_W("Write error"))
TJS_MSG_DECL(TJSReadError, TJS_W("Read error"))
TJS_MSG_DECL(TJSSeekError, TJS_W("Seek error"))
TJS_MSG_DECL(TJSByteCodeBroken, TJS_W("Bytecode file is corrupted"))
TJS_MSG_DECL(TJSObjectHashMapLogVersionMismatch, TJS_W("Object hash map log version mismatch"))
TJS_MSG_DECL(TJSCurruptedObjectHashMapLog, TJS_W("Corrupted object hash map log"))
TJS_MSG_DECL(TJSUnknownFailure, TJS_W("Unknown failure"))
TJS_MSG_DECL(TJSUnknownPackUnpackTemplateCharcter, TJS_W("Unknown pack/unpack template character"))
TJS_MSG_DECL(TJSUnknownBitStringCharacter, TJS_W("Unknown bit string character"))
TJS_MSG_DECL(TJSUnknownHexStringCharacter, TJS_W("Unknown hex string character"))
TJS_MSG_DECL(TJSNotSupportedUuencode, TJS_W("uuencode not supported"))
TJS_MSG_DECL(TJSNotSupportedBER, TJS_W("BER not supported"))
TJS_MSG_DECL(TJSNotSupportedUnpackLP, TJS_W("Unpack LP not supported"))
TJS_MSG_DECL(TJSNotSupportedUnpackP, TJS_W("Unpack P not supported"))
#endif
